// @ts-ignore - PrismaClient is generated by `prisma generate`
import { PrismaClient } from '@prisma/client'

/**
 * Prisma Client singleton with lazy initialization and connection pooling.
 * 
 * Uses a Proxy pattern to defer PrismaClient creation until first access,
 * ensuring environment variables are loaded before database connection.
 * 
 * @remarks
 * - Uses Prisma 7 with MariaDB adapter for MySQL compatibility
 * - Implements connection pooling (limit: 20, timeout: 30s)
 * - Prevents client-side bundling via dynamic require()
 * - Shares single instance across application to avoid pool exhaustion
 */

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined
}

interface DatabaseConfig {
  host: string
  port: number
  user: string
  password: string
  database: string
}

/**
 * Parses MySQL connection string into configuration object.
 * 
 * @param url - MySQL connection string (mysql://user:pass@host:port/db)
 * @returns Parsed database configuration
 * @throws {Error} If URL is invalid or code runs on client-side
 */
const parseDatabaseUrl = (url: string | undefined): DatabaseConfig => {
  if (typeof window !== 'undefined') {
    throw new Error('Prisma can only be used on the server-side')
  }
  
  if (!url || typeof url !== 'string' || url.trim() === '') {
    throw new Error('DATABASE_URL is not defined. Please check your .env file.')
  }
  
  if (url === 'undefined' || url === 'null') {
    throw new Error('DATABASE_URL appears to be undefined. Please check your .env file.')
  }
  
  try {
    const dbUrl = new URL(url.replace('mysql://', 'http://'))
    return {
      host: dbUrl.hostname,
      port: parseInt(dbUrl.port || '3306', 10),
      user: dbUrl.username,
      password: dbUrl.password,
      database: dbUrl.pathname.slice(1),
    }
  } catch (error) {
    throw new Error(`Invalid DATABASE_URL format: ${error instanceof Error ? error.message : String(error)}`)
  }
}

/**
 * Creates a new PrismaClient instance with MariaDB adapter.
 * 
 * @returns Configured PrismaClient instance
 * @throws {Error} If DATABASE_URL is missing or adapter fails to load
 */
const createPrismaClient = (): PrismaClient => {
  if (typeof window !== 'undefined') {
    throw new Error('Prisma can only be used on the server-side')
  }
  
  const databaseUrl = process.env.DATABASE_URL
  if (!databaseUrl) {
    throw new Error(
      'DATABASE_URL environment variable is required. ' +
      'Please check your .env file and ensure it contains: DATABASE_URL="mysql://user:password@host:port/database"'
    )
  }
  
  try {
    const dbConfig = parseDatabaseUrl(databaseUrl)
    const { PrismaMariaDb } = require('@prisma/adapter-mariadb')
    
    const adapter = new PrismaMariaDb({
      ...dbConfig,
      connectionLimit: 20,
      acquireTimeout: 30000,
      timeout: 30000,
    })
    
    return new PrismaClient({ adapter })
  } catch (error) {
    if (error instanceof Error && error.message.includes('DATABASE_URL')) {
      throw error
    }
    throw new Error(`Failed to create Prisma client: ${error instanceof Error ? error.message : String(error)}`)
  }
}

/**
 * Lazy initialization getter for PrismaClient.
 * Creates instance on first access and reuses it via globalThis.
 */
function getPrisma(): PrismaClient {
  if (!globalForPrisma.prisma) {
    if (!process.env.DATABASE_URL) {
      throw new Error(
        'DATABASE_URL environment variable is required. ' +
        'Please check your .env file and ensure it contains: DATABASE_URL="mysql://user:password@host:port/database"'
      )
    }
    globalForPrisma.prisma = createPrismaClient()
  }
  return globalForPrisma.prisma
}

/**
 * Exported Prisma client with lazy initialization via Proxy.
 * 
 * @example
 * ```ts
 * import { prisma } from '@/lib/prisma'
 * const users = await prisma.user.findMany()
 * ```
 */
export const prisma = new Proxy({} as PrismaClient, {
  get(_target, prop) {
    const client = getPrisma()
    const value = client[prop as keyof PrismaClient]
    return typeof value === 'function' ? value.bind(client) : value
  },
})
